CREATE TABLE table1 (id INTEGER PRIMARY KEY, name TEXT, columna INTEGER, columnb INTEGER);
CREATE TABLE table2 (id INTEGER PRIMARY KEY, name TEXT, columnc INTEGER, columnd INTEGER);
CREATE TABLE table3 (id INTEGER PRIMARY KEY, name TEXT, columne INTEGER, columnf INTEGER);
 